dist: trusty

services:
  - docker

before_install:
  - git rev-list --all --count > .version
  - echo building image -\> ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}
  - docker build --no-cache -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
  - docker tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} ${TRAVIS_REPO_SLUG}:latest

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}


